import type { Metadata } from "next";
import type { Viewport } from 'next'
import localFont from "next/font/local";
import "./globals.css";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MxM Ai",
  description: "Generated by MxM Ai Flow",
  //viewport: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no",

  // mobileWebAppCapable: "yes",
  //appleMobileWebAppStatusBarStyle: "#050505",
};
export const viewport: Viewport = {
  themeColor: '#050505',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}
export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-theme-dark`}
      >
        {children}
      </body>
    </html>
  );
}
